-- GENERATED by npm run forge:dump. DO NOT EDIT.
-- Source: packages/content/content.sqlite
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE schema_migrations (
	version    TEXT NOT NULL PRIMARY KEY,
	applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
INSERT INTO schema_migrations VALUES('0001_core_vocab','2026-09-20T19:14:04Z');
INSERT INTO schema_migrations VALUES('0002_seed_core_vocab','2026-09-20T19:14:04Z');
INSERT INTO schema_migrations VALUES('0003_entity_comment','2026-09-20T20:59:42Z');
CREATE TABLE attribute (
	id           INTEGER PRIMARY KEY AUTOINCREMENT,
	slug         TEXT NOT NULL UNIQUE
		CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9]*'),
	label        TEXT NOT NULL CHECK (length(label) > 0),
	abbreviation TEXT NOT NULL CHECK (length(abbreviation) > 0),
	description  TEXT NOT NULL DEFAULT '',
	sort_order   INTEGER NOT NULL DEFAULT 0
, comment TEXT NOT NULL DEFAULT '');
INSERT INTO attribute VALUES(1,'mgh','Might','MGH','',1,'');
INSERT INTO attribute VALUES(2,'dex','Dexterity','DEX','',2,'');
INSERT INTO attribute VALUES(3,'kno','Knowledge','KNO','',3,'');
INSERT INTO attribute VALUES(4,'foc','Focus','FOC','',4,'');
INSERT INTO attribute VALUES(5,'pre','Presence','PRE','',5,'');
INSERT INTO attribute VALUES(6,'lck','Luck','LCK','',6,'');
CREATE TABLE skill (
	id                   INTEGER PRIMARY KEY AUTOINCREMENT,
	slug                 TEXT NOT NULL UNIQUE
		CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9]*'),
	label                TEXT NOT NULL CHECK (length(label) > 0),
	description          TEXT NOT NULL DEFAULT '',
	attribute_id         INTEGER NOT NULL REFERENCES attribute (id),
	specialization_mode  TEXT NOT NULL
		CHECK (specialization_mode IN ('none', 'fixed', 'free', 'parameterized')),
	is_secondary         INTEGER NOT NULL DEFAULT 0 CHECK (is_secondary IN (0, 1)),
	sort_order           INTEGER NOT NULL DEFAULT 0,
	foundry_id           TEXT NOT NULL UNIQUE
		CHECK (length(foundry_id) = 16 AND foundry_id NOT GLOB '*[^A-Za-z0-9]*')
, comment TEXT NOT NULL DEFAULT '');
INSERT INTO skill VALUES(1,'arcana','Arcana','',3,'free',0,1,'kdmskl00arcana00','');
INSERT INTO skill VALUES(2,'connect','Connect','',5,'free',0,2,'kdmskl00connect0','');
INSERT INTO skill VALUES(3,'conduct','Conduct','',5,'fixed',0,3,'kdmskl00conduct0','');
INSERT INTO skill VALUES(4,'convince','Convince','',5,'fixed',0,4,'kdmskl0convince0','');
INSERT INTO skill VALUES(5,'craft','Craft','',2,'free',0,5,'kdmskl000craft00','');
INSERT INTO skill VALUES(6,'exert','Exert','',1,'none',0,6,'kdmskl000exert00','');
INSERT INTO skill VALUES(7,'guile','Guile','',3,'fixed',0,7,'kdmskl000guile00','');
INSERT INTO skill VALUES(8,'heal','Heal','',3,'fixed',0,8,'kdmskl0000heal00','');
INSERT INTO skill VALUES(9,'investigate','Investigate','',3,'fixed',0,9,'kdmsklinvestiga0','');
INSERT INTO skill VALUES(10,'lore','Lore','',3,'free',0,10,'kdmskl0000lore00','');
INSERT INTO skill VALUES(11,'notice','Notice','',4,'fixed',0,11,'kdmskl00notice00','');
INSERT INTO skill VALUES(12,'prowl','Prowl','',2,'fixed',0,12,'kdmskl000prowl00','');
INSERT INTO skill VALUES(13,'punch','Punch','',1,'none',0,13,'kdmskl000punch00','');
INSERT INTO skill VALUES(14,'shoot','Shoot','',2,'none',0,14,'kdmskl000shoot00','');
INSERT INTO skill VALUES(15,'stab','Stab','',1,'none',0,15,'kdmskl0000stab00','');
INSERT INTO skill VALUES(16,'survive','Survive','',4,'parameterized',0,16,'kdmskl0survive00','');
INSERT INTO skill VALUES(17,'travel','Travel','',1,'parameterized',0,17,'kdmskl00travel00','');
INSERT INTO skill VALUES(18,'work','Work','',1,'free',0,18,'kdmskl0000work00','');
INSERT INTO skill VALUES(19,'worship','Worship','',5,'free',0,19,'kdmskl0worship00','');
CREATE TABLE specialization (
	id          INTEGER PRIMARY KEY AUTOINCREMENT,
	slug        TEXT NOT NULL UNIQUE
		CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9.]*'),
	label       TEXT NOT NULL CHECK (length(label) > 0),
	description TEXT NOT NULL DEFAULT '',
	skill_id    INTEGER NOT NULL REFERENCES skill (id) ON DELETE CASCADE,
	parameter   TEXT CHECK (parameter IS NULL OR parameter IN ('environment', 'pantheon', 'culture')),
	sort_order  INTEGER NOT NULL DEFAULT 0,
	foundry_id  TEXT NOT NULL UNIQUE
		CHECK (length(foundry_id) = 16 AND foundry_id NOT GLOB '*[^A-Za-z0-9]*')
, comment TEXT NOT NULL DEFAULT '');
INSERT INTO specialization VALUES(1,'conduct.bureaucracy','Bureaucracy','',3,NULL,1,'kdmsp00000000001','');
INSERT INTO specialization VALUES(2,'conduct.etiquette','Etiquette','',3,NULL,2,'kdmsp00000000002','');
INSERT INTO specialization VALUES(3,'conduct.law','Law','',3,NULL,3,'kdmsp00000000003','');
INSERT INTO specialization VALUES(4,'conduct.organizations','Organizations','',3,NULL,4,'kdmsp00000000004','');
INSERT INTO specialization VALUES(5,'conduct.politics','Politics','',3,NULL,5,'kdmsp00000000005','');
INSERT INTO specialization VALUES(6,'conduct.rumors','Rumors','',3,NULL,6,'kdmsp00000000006','');
INSERT INTO specialization VALUES(7,'conduct.streetwise','Streetwise','',3,NULL,7,'kdmsp00000000007','');
INSERT INTO specialization VALUES(8,'convince.charm','Charm','',4,NULL,1,'kdmsp00000000008','');
INSERT INTO specialization VALUES(9,'convince.command','Command','',4,NULL,2,'kdmsp00000000009','');
INSERT INTO specialization VALUES(10,'convince.deception','Deception','',4,NULL,3,'kdmsp00000000010','');
INSERT INTO specialization VALUES(11,'convince.haggle','Haggle','',4,NULL,4,'kdmsp00000000011','');
INSERT INTO specialization VALUES(12,'convince.intimidation','Intimidation','',4,NULL,5,'kdmsp00000000012','');
INSERT INTO specialization VALUES(13,'convince.performance','Performance','',4,NULL,6,'kdmsp00000000013','');
INSERT INTO specialization VALUES(14,'convince.persuasion','Persuasion','',4,NULL,7,'kdmsp00000000014','');
INSERT INTO specialization VALUES(15,'guile.disguise','Disguise','',7,NULL,1,'kdmsp00000000015','');
INSERT INTO specialization VALUES(16,'guile.forgery','Forgery','',7,NULL,2,'kdmsp00000000016','');
INSERT INTO specialization VALUES(17,'guile.fraud','Fraud','',7,NULL,3,'kdmsp00000000017','');
INSERT INTO specialization VALUES(18,'guile.gambling','Gambling','',7,NULL,4,'kdmsp00000000018','');
INSERT INTO specialization VALUES(19,'guile.poisons','Poisons','',7,NULL,5,'kdmsp00000000019','');
INSERT INTO specialization VALUES(20,'guile.traps','Traps','',7,NULL,6,'kdmsp00000000020','');
INSERT INTO specialization VALUES(21,'heal.diagnosis','Diagnosis','',8,NULL,1,'kdmsp00000000021','');
INSERT INTO specialization VALUES(22,'heal.firstaid','First Aid','',8,NULL,2,'kdmsp00000000022','');
INSERT INTO specialization VALUES(23,'heal.pharmacology','Pharmacology','',8,NULL,3,'kdmsp00000000023','');
INSERT INTO specialization VALUES(24,'heal.psychology','Psychology','',8,NULL,4,'kdmsp00000000024','');
INSERT INTO specialization VALUES(25,'heal.rehabilitation','Rehabilitation','',8,NULL,5,'kdmsp00000000025','');
INSERT INTO specialization VALUES(26,'heal.surgery','Surgery','',8,NULL,6,'kdmsp00000000026','');
INSERT INTO specialization VALUES(27,'heal.toxicology','Toxicology','',8,NULL,7,'kdmsp00000000027','');
INSERT INTO specialization VALUES(28,'investigate.appraisal','Appraisal','',9,NULL,1,'kdmsp00000000028','');
INSERT INTO specialization VALUES(29,'investigate.cryptography','Cryptography','',9,NULL,2,'kdmsp00000000029','');
INSERT INTO specialization VALUES(30,'investigate.investigation','Investigation','',9,NULL,3,'kdmsp00000000030','');
INSERT INTO specialization VALUES(31,'investigate.libraryuse','Library Use','',9,NULL,4,'kdmsp00000000031','');
INSERT INTO specialization VALUES(32,'investigate.research','Research','',9,NULL,5,'kdmsp00000000032','');
INSERT INTO specialization VALUES(33,'investigate.search','Search','',9,NULL,6,'kdmsp00000000033','');
INSERT INTO specialization VALUES(34,'notice.anomalies','Anomalies','',11,NULL,1,'kdmsp00000000034','');
INSERT INTO specialization VALUES(35,'notice.awareness','Awareness','',11,NULL,2,'kdmsp00000000035','');
INSERT INTO specialization VALUES(36,'notice.detail','Detail','',11,NULL,3,'kdmsp00000000036','');
INSERT INTO specialization VALUES(37,'notice.farsight','Farsight','',11,NULL,4,'kdmsp00000000037','');
INSERT INTO specialization VALUES(38,'notice.hidden','Hidden','',11,NULL,5,'kdmsp00000000038','');
INSERT INTO specialization VALUES(39,'notice.insight','Insight','',11,NULL,6,'kdmsp00000000039','');
INSERT INTO specialization VALUES(40,'notice.listen','Listen','',11,NULL,7,'kdmsp00000000040','');
INSERT INTO specialization VALUES(41,'prowl.backstabbing','Backstabbing','',12,NULL,1,'kdmsp00000000041','');
INSERT INTO specialization VALUES(42,'prowl.climbing','Climbing','',12,NULL,2,'kdmsp00000000042','');
INSERT INTO specialization VALUES(43,'prowl.hide','Hide','',12,NULL,3,'kdmsp00000000043','');
INSERT INTO specialization VALUES(44,'prowl.lockpicking','Lockpicking','',12,NULL,4,'kdmsp00000000044','');
INSERT INTO specialization VALUES(45,'prowl.sleightofhand','Sleight of Hand','',12,NULL,5,'kdmsp00000000045','');
INSERT INTO specialization VALUES(46,'prowl.sneaking','Sneaking','',12,NULL,6,'kdmsp00000000046','');
INSERT INTO specialization VALUES(47,'survive.foraging','Foraging','',16,NULL,1,'kdmsp00000000047','');
INSERT INTO specialization VALUES(48,'survive.scouting','Scouting','',16,NULL,2,'kdmsp00000000048','');
INSERT INTO specialization VALUES(49,'survive.shelter','Shelter','',16,NULL,3,'kdmsp00000000049','');
INSERT INTO specialization VALUES(50,'survive.tracking','Tracking','',16,NULL,4,'kdmsp00000000050','');
INSERT INTO specialization VALUES(51,'travel.hiking','Hiking','',17,NULL,1,'kdmsp00000000051','');
INSERT INTO specialization VALUES(52,'travel.riding','Riding','',17,NULL,2,'kdmsp00000000052','');
INSERT INTO specialization VALUES(53,'travel.driving','Driving','',17,NULL,3,'kdmsp00000000053','');
INSERT INTO specialization VALUES(54,'travel.sailing','Sailing','',17,NULL,4,'kdmsp00000000054','');
INSERT INTO specialization VALUES(55,'travel.navigation','Navigation','',17,NULL,5,'kdmsp00000000055','');
INSERT INTO specialization VALUES(56,'travel.orientation','Orientation','',17,NULL,6,'kdmsp00000000056','');
CREATE TABLE class (
	id                     INTEGER PRIMARY KEY AUTOINCREMENT,
	slug                   TEXT NOT NULL UNIQUE
		CHECK (length(slug) > 0 AND slug NOT GLOB '*[^a-z0-9-]*'),
	label                  TEXT NOT NULL CHECK (length(label) > 0),
	description            TEXT NOT NULL DEFAULT '',
	is_full                INTEGER NOT NULL DEFAULT 0 CHECK (is_full IN (0, 1)),
	is_partial             INTEGER NOT NULL DEFAULT 0 CHECK (is_partial IN (0, 1)),
	attack_progression     TEXT,
	skill_points_per_level INTEGER,
	hit_die                TEXT,
	sort_order             INTEGER NOT NULL DEFAULT 0,
	foundry_id             TEXT NOT NULL UNIQUE
		CHECK (length(foundry_id) = 16 AND foundry_id NOT GLOB '*[^A-Za-z0-9]*'), comment TEXT NOT NULL DEFAULT '',
	CHECK (is_full = 1 OR is_partial = 1)
);
INSERT INTO class VALUES(1,'warrior','Warrior','',1,1,NULL,NULL,NULL,1,'kdmcls0warrior00','');
INSERT INTO class VALUES(2,'expert','Expert','',1,1,NULL,NULL,NULL,2,'kdmcls00expert00','');
INSERT INTO class VALUES(3,'queran-arcanist','Queran Arcanist','',1,1,NULL,NULL,NULL,3,'kdmcls0queranar0','');
INSERT INTO class VALUES(4,'elementalist','Elementalist','',1,1,NULL,NULL,NULL,4,'kdmcls0elemental','');
INSERT INTO class VALUES(5,'necromancer','Necromancer','',1,1,NULL,NULL,NULL,5,'kdmcls0necroman0','');
INSERT INTO class VALUES(6,'priest','Priest','',0,1,NULL,NULL,NULL,6,'kdmcls00priest00','');
INSERT INTO class VALUES(7,'wise','Wise','',0,1,NULL,NULL,NULL,7,'kdmcls0000wise00','');
INSERT INTO class VALUES(8,'accursed','Accursed','',0,1,NULL,NULL,NULL,8,'kdmcls0accursed0','');
INSERT INTO class VALUES(9,'duelist','Duelist','',0,1,NULL,NULL,NULL,9,'kdmcls0duelist00','');
INSERT INTO class VALUES(10,'empath','Empath','',0,1,NULL,NULL,NULL,10,'kdmcls00empath00','');
INSERT INTO class VALUES(11,'rune-guardian','Rune Guardian','',0,1,NULL,NULL,NULL,11,'kdmcls0runeguard','');
INSERT INTO class VALUES(12,'beast','Beast','',0,1,NULL,NULL,NULL,12,'kdmcls000beast00','');
CREATE TABLE translation (
	id          INTEGER PRIMARY KEY AUTOINCREMENT,
	entity_kind TEXT NOT NULL
		CHECK (entity_kind IN (
			'attribute', 'skill', 'specialization', 'class',
			'background', 'region', 'focus', 'power', 'condition', 'injury', 'race'
		)),
	entity_id   INTEGER NOT NULL,
	locale      TEXT NOT NULL CHECK (locale != 'en' AND length(locale) > 0),
	field       TEXT NOT NULL CHECK (field IN ('label', 'abbreviation', 'description')),
	value       TEXT NOT NULL CHECK (length(value) > 0),
	UNIQUE (entity_kind, entity_id, locale, field)
);
INSERT INTO translation VALUES(1,'attribute',1,'ru','label','Мощь');
INSERT INTO translation VALUES(2,'attribute',1,'ru','abbreviation','МЩ');
INSERT INTO translation VALUES(3,'attribute',2,'ru','label','Ловкость');
INSERT INTO translation VALUES(4,'attribute',2,'ru','abbreviation','ЛВК');
INSERT INTO translation VALUES(5,'attribute',3,'ru','label','Знание');
INSERT INTO translation VALUES(6,'attribute',3,'ru','abbreviation','ЗНН');
INSERT INTO translation VALUES(7,'attribute',4,'ru','label','Фокус');
INSERT INTO translation VALUES(8,'attribute',4,'ru','abbreviation','ФКС');
INSERT INTO translation VALUES(9,'attribute',5,'ru','label','Присутствие');
INSERT INTO translation VALUES(10,'attribute',5,'ru','abbreviation','ПРС');
INSERT INTO translation VALUES(11,'attribute',6,'ru','label','Удача');
INSERT INTO translation VALUES(12,'attribute',6,'ru','abbreviation','УДЧ');
INSERT INTO translation VALUES(13,'skill',1,'ru','label','Аркана');
INSERT INTO translation VALUES(14,'skill',2,'ru','label','Связи');
INSERT INTO translation VALUES(15,'skill',3,'ru','label','Обхождение');
INSERT INTO translation VALUES(16,'skill',4,'ru','label','Убеждение');
INSERT INTO translation VALUES(17,'skill',5,'ru','label','Ремесло');
INSERT INTO translation VALUES(18,'skill',6,'ru','label','Натуга');
INSERT INTO translation VALUES(19,'skill',7,'ru','label','Хитрость');
INSERT INTO translation VALUES(20,'skill',8,'ru','label','Лечение');
INSERT INTO translation VALUES(21,'skill',9,'ru','label','Расследование');
INSERT INTO translation VALUES(22,'skill',10,'ru','label','Предания');
INSERT INTO translation VALUES(23,'skill',11,'ru','label','Внимательность');
INSERT INTO translation VALUES(24,'skill',12,'ru','label','Скрытность');
INSERT INTO translation VALUES(25,'skill',13,'ru','label','Кулачный бой');
INSERT INTO translation VALUES(26,'skill',14,'ru','label','Стрельба');
INSERT INTO translation VALUES(27,'skill',15,'ru','label','Холодное оружие');
INSERT INTO translation VALUES(28,'skill',16,'ru','label','Выживание');
INSERT INTO translation VALUES(29,'skill',17,'ru','label','Путешествия');
INSERT INTO translation VALUES(30,'skill',18,'ru','label','Труд');
INSERT INTO translation VALUES(31,'skill',19,'ru','label','Поклонение');
INSERT INTO translation VALUES(32,'class',1,'ru','label','Воин');
INSERT INTO translation VALUES(33,'class',2,'ru','label','Эксперт');
INSERT INTO translation VALUES(34,'class',3,'ru','label','Кверанский арканист');
INSERT INTO translation VALUES(35,'class',4,'ru','label','Элементалист');
INSERT INTO translation VALUES(36,'class',5,'ru','label','Некромант');
INSERT INTO translation VALUES(37,'class',6,'ru','label','Жрец');
INSERT INTO translation VALUES(38,'class',7,'ru','label','Ведун');
INSERT INTO translation VALUES(39,'class',8,'ru','label','Проклятый');
INSERT INTO translation VALUES(40,'class',9,'ru','label','Дуэлянт');
INSERT INTO translation VALUES(41,'class',10,'ru','label','Эмпат');
INSERT INTO translation VALUES(42,'class',11,'ru','label','Рунный защитник');
INSERT INTO translation VALUES(43,'class',12,'ru','label','Зверь');
CREATE TRIGGER translation_insert_entity_exists
BEFORE INSERT ON translation
BEGIN
	SELECT CASE
		WHEN NEW.entity_kind = 'attribute'
			AND NOT EXISTS (SELECT 1 FROM attribute WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: attribute not found')
		WHEN NEW.entity_kind = 'skill'
			AND NOT EXISTS (SELECT 1 FROM skill WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: skill not found')
		WHEN NEW.entity_kind = 'specialization'
			AND NOT EXISTS (SELECT 1 FROM specialization WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: specialization not found')
		WHEN NEW.entity_kind = 'class'
			AND NOT EXISTS (SELECT 1 FROM class WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: class not found')
	END;
END;
CREATE TRIGGER translation_update_entity_exists
BEFORE UPDATE OF entity_kind, entity_id ON translation
BEGIN
	SELECT CASE
		WHEN NEW.entity_kind = 'attribute'
			AND NOT EXISTS (SELECT 1 FROM attribute WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: attribute not found')
		WHEN NEW.entity_kind = 'skill'
			AND NOT EXISTS (SELECT 1 FROM skill WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: skill not found')
		WHEN NEW.entity_kind = 'specialization'
			AND NOT EXISTS (SELECT 1 FROM specialization WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: specialization not found')
		WHEN NEW.entity_kind = 'class'
			AND NOT EXISTS (SELECT 1 FROM class WHERE id = NEW.entity_id)
			THEN RAISE(ABORT, 'translation.entity_id: class not found')
	END;
END;
CREATE TRIGGER attribute_delete_translations
AFTER DELETE ON attribute
BEGIN
	DELETE FROM translation WHERE entity_kind = 'attribute' AND entity_id = OLD.id;
END;
CREATE TRIGGER skill_delete_translations
AFTER DELETE ON skill
BEGIN
	DELETE FROM translation WHERE entity_kind = 'skill' AND entity_id = OLD.id;
END;
CREATE TRIGGER specialization_delete_translations
AFTER DELETE ON specialization
BEGIN
	DELETE FROM translation WHERE entity_kind = 'specialization' AND entity_id = OLD.id;
END;
CREATE TRIGGER class_delete_translations
AFTER DELETE ON class
BEGIN
	DELETE FROM translation WHERE entity_kind = 'class' AND entity_id = OLD.id;
END;

COMMIT;
PRAGMA foreign_keys=ON;
