/**
 * Regenerates packages/content/dump.sql from content.sqlite.
 *
 * Uses the sqlite3 CLI for a stable, reviewable dump. Schema statements come
 * first (SQLite's default .dump order), then data.
 *
 * Usage: npm run forge:dump
 */
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dbPath = join(root, "packages/content/content.sqlite");
const outPath = join(root, "packages/content/dump.sql");

if (!existsSync(dbPath)) {
  console.error(`missing ${dbPath}; run the Forge API once to migrate and seed`);
  process.exit(1);
}

const raw = execFileSync("sqlite3", [dbPath, ".dump"], { encoding: "utf8" });
const lines = raw.split("\n").filter((line) => {
  if (line.startsWith("PRAGMA foreign_keys")) return false;
  if (line.includes("sqlite_sequence")) return false;
  return true;
});

const header = [
  "-- GENERATED by npm run forge:dump. DO NOT EDIT.",
  "-- Source: packages/content/content.sqlite",
  "PRAGMA foreign_keys=OFF;",
  "BEGIN TRANSACTION;",
];

const body = lines.filter(
  (line) =>
    line !== "BEGIN TRANSACTION;" &&
    line !== "COMMIT;" &&
    line !== "PRAGMA foreign_keys=OFF;" &&
    !line.startsWith("--"),
);

const out = [...header, ...body, "COMMIT;", "PRAGMA foreign_keys=ON;", ""].join("\n");
writeFileSync(outPath, out, "utf8");
console.log(`wrote ${outPath} (${body.length} statements)`);
