// Package export emits reviewable artefacts from the SQLite content database.
// Markdown is the barebones rulebook view for reading and printing.
package export

import (
	"fmt"
	"io"
	"strings"
)

const generatedHeader = "<!-- GENERATED by Kedom Forge. DO NOT EDIT — edit in Forge and re-export. -->\n"

// AttributeRow is display-resolved attribute data for markdown.
type AttributeRow struct {
	Slug         string
	Label        string
	Abbreviation string
	Description  string
}

// SpecRow is a specialisation nested under a skill.
type SpecRow struct {
	Slug        string
	Label       string
	Description string
	Parameter   string
}

// SkillRow is a skill with its specialisations.
type SkillRow struct {
	Slug               string
	Label              string
	Description        string
	AttributeSlug      string
	AttributeLabel     string
	SpecializationMode string
	IsSecondary        bool
	Specs              []SpecRow
}

// ClassRow is a class roster entry.
type ClassRow struct {
	Slug        string
	Label       string
	Description string
	IsFull      bool
	IsPartial   bool
}

// RulebookInput is the resolved (locale-aware) content for a barebones rulebook.
type RulebookInput struct {
	Locale     string
	Attributes []AttributeRow
	Skills     []SkillRow
	Classes    []ClassRow
}

// WriteRulebook writes a single barebones markdown rulebook.
func WriteRulebook(w io.Writer, in RulebookInput) error {
	locale := in.Locale
	if locale == "" {
		locale = "en"
	}
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n# Kedom — core vocabulary\n\n")
	b.WriteString(fmt.Sprintf("Locale: `%s`. Skeletal reference from Forge; not a finished rulebook.\n", locale))

	b.WriteString("\n## Attributes\n")
	for _, a := range in.Attributes {
		b.WriteString(fmt.Sprintf("\n### %s (%s)\n\n", a.Label, a.Abbreviation))
		b.WriteString(fmt.Sprintf("`%s`\n\n", a.Slug))
		writeProse(&b, a.Description)
	}

	b.WriteString("\n## Skills\n")
	for _, s := range in.Skills {
		b.WriteString(fmt.Sprintf("\n### %s\n\n", s.Label))
		b.WriteString(fmt.Sprintf("`%s` · %s · mode `%s`", s.Slug, s.AttributeLabel, s.SpecializationMode))
		if s.IsSecondary {
			b.WriteString(" · secondary")
		}
		b.WriteString("\n\n")
		writeProse(&b, s.Description)
		if len(s.Specs) == 0 {
			continue
		}
		b.WriteString("#### Specialisations\n\n")
		for _, sp := range s.Specs {
			line := fmt.Sprintf("- **%s** (`%s`)", sp.Label, sp.Slug)
			if sp.Parameter != "" {
				line += fmt.Sprintf(" — parameter `%s`", sp.Parameter)
			}
			b.WriteString(line + "\n")
			if strings.TrimSpace(sp.Description) != "" {
				b.WriteString("  \n  " + flattenProse(sp.Description) + "\n")
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## Classes\n")
	for _, c := range in.Classes {
		b.WriteString(fmt.Sprintf("\n### %s\n\n", c.Label))
		kinds := make([]string, 0, 2)
		if c.IsFull {
			kinds = append(kinds, "full")
		}
		if c.IsPartial {
			kinds = append(kinds, "partial")
		}
		b.WriteString(fmt.Sprintf("`%s`", c.Slug))
		if len(kinds) > 0 {
			b.WriteString(" · " + strings.Join(kinds, " · "))
		}
		b.WriteString("\n\n")
		writeProse(&b, c.Description)
	}

	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// WriteAttributesFile writes attributes.md.
func WriteAttributesFile(w io.Writer, in RulebookInput) error {
	locale := localeOrEN(in.Locale)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("\n# Attributes\n\nLocale: `%s`\n", locale))
	for _, a := range in.Attributes {
		b.WriteString(fmt.Sprintf("\n## %s (%s)\n\n`%s`\n\n", a.Label, a.Abbreviation, a.Slug))
		writeProse(&b, a.Description)
	}
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// WriteSkillsFile writes skills.md.
func WriteSkillsFile(w io.Writer, in RulebookInput) error {
	locale := localeOrEN(in.Locale)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("\n# Skills\n\nLocale: `%s`\n", locale))
	for _, s := range in.Skills {
		b.WriteString(fmt.Sprintf("\n## %s\n\n", s.Label))
		b.WriteString(fmt.Sprintf("`%s` · %s · mode `%s`", s.Slug, s.AttributeLabel, s.SpecializationMode))
		if s.IsSecondary {
			b.WriteString(" · secondary")
		}
		b.WriteString("\n\n")
		writeProse(&b, s.Description)
		if len(s.Specs) == 0 {
			continue
		}
		b.WriteString("### Specialisations\n\n")
		for _, sp := range s.Specs {
			line := fmt.Sprintf("- **%s** (`%s`)", sp.Label, sp.Slug)
			if sp.Parameter != "" {
				line += fmt.Sprintf(" — parameter `%s`", sp.Parameter)
			}
			b.WriteString(line + "\n")
			if strings.TrimSpace(sp.Description) != "" {
				b.WriteString("  \n  " + flattenProse(sp.Description) + "\n")
			}
		}
	}
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// WriteClassesFile writes classes.md.
func WriteClassesFile(w io.Writer, in RulebookInput) error {
	locale := localeOrEN(in.Locale)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("\n# Classes\n\nLocale: `%s`\n", locale))
	for _, c := range in.Classes {
		b.WriteString(fmt.Sprintf("\n## %s\n\n", c.Label))
		kinds := make([]string, 0, 2)
		if c.IsFull {
			kinds = append(kinds, "full")
		}
		if c.IsPartial {
			kinds = append(kinds, "partial")
		}
		b.WriteString(fmt.Sprintf("`%s`", c.Slug))
		if len(kinds) > 0 {
			b.WriteString(" · " + strings.Join(kinds, " · "))
		}
		b.WriteString("\n\n")
		writeProse(&b, c.Description)
	}
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func localeOrEN(locale string) string {
	if locale == "" {
		return "en"
	}
	return locale
}

func writeProse(b *strings.Builder, text string) {
	text = strings.TrimSpace(text)
	if text == "" {
		b.WriteString("_(no description yet)_\n")
		return
	}
	b.WriteString(text)
	if !strings.HasSuffix(text, "\n") {
		b.WriteString("\n")
	}
}

func flattenProse(text string) string {
	return strings.Join(strings.Fields(strings.TrimSpace(text)), " ")
}
