// Package export emits reviewable artefacts from the SQLite content database.
package export

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/yuin/goldmark"
	"gopkg.in/yaml.v3"
)

const packHeader = "# GENERATED by Kedom Forge. DO NOT EDIT — edit in Forge and re-export.\n"

// PackTalent is a talent row for YAML export.
type PackTalent struct {
	Slug        string
	Label       string
	Description string
	FoundryID   string
	Category    string
	GrantsJSON  string
	EffectsJSON string
}

// PackRegionCulture is a culture entry under a region.
type PackRegionCulture struct {
	Slug            string
	Weight          int64
	BackgroundSlugs []string
}

// PackRegion is a region origin document.
type PackRegion struct {
	Slug        string
	Label       string
	Description string
	FoundryID   string
	BannerImg   string
	Cultures    []PackRegionCulture
}

// PackRace is a culture (race) origin document.
type PackRace struct {
	Slug        string
	Label       string
	Description string
	FoundryID   string
	TalentSlug  string
	ClassSlugs  []string
}

// PackGrowth is one 1d8 growth row.
type PackGrowth struct {
	SkillKey string
	SpecSlug string
}

// PackBackground is a background origin document.
type PackBackground struct {
	Slug         string
	Label        string
	Description  string
	FoundryID    string
	FreeSkillKey string
	FreeSpecSlug string
	Growth       [8]PackGrowth
}

// PackClass is a class origin document.
type PackClass struct {
	Slug                  string
	Label                 string
	Description           string
	FoundryID             string
	IsFull                bool
	HitDie                string
	HitDiePriority        int64
	TalentSlugs           []string
	TalentPicksWarrior    int64
	TalentPicksExpert     int64
	TalentPicksAny        int64
	SavePrimary           string
	SavePrimaryPriority   int64
	SaveSecondary         string
	SaveSecondaryPriority int64
	EffortSkillKey        string
	EffortAbilityKeys     []string
	SlotsByLevel          []int64
}

// PackArt is an art item document.
type PackArt struct {
	Slug        string
	Label       string
	Description string
	FoundryID   string
	ClassSlug   string
	Commitment  string
	EffectsJSON string
}

// PackInput is everything needed to write origins + talents + arts packs.
type PackInput struct {
	Talents     []PackTalent
	Arts        []PackArt
	Regions     []PackRegion
	Races       []PackRace
	Backgrounds []PackBackground
	Classes     []PackClass
}

func emptyArtsBlock() map[string]any {
	return map[string]any{
		"skillKey": "", "abilityKeys": []string{},
		"slotsByLevel": []int{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		"receiveTableKey": "", "artKeys": []string{},
	}
}

// WritePacks writes YAML sources under outDir/origins, outDir/talents, and outDir/arts.
// Each pack source directory is removed and recreated first so deleted entities
// cannot leave stale YAML behind for packs:build.
func WritePacks(outDir string, in PackInput) error {
	originsDir := filepath.Join(outDir, "origins")
	talentsDir := filepath.Join(outDir, "talents")
	artsDir := filepath.Join(outDir, "arts")
	for _, dir := range []string{originsDir, talentsDir, artsDir} {
		if err := os.RemoveAll(dir); err != nil {
			return fmt.Errorf("clean pack source %s: %w", dir, err)
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	md := goldmark.New()

	for _, t := range in.Talents {
		doc := map[string]any{
			"_id":  t.FoundryID,
			"name": t.Label,
			"type": "talent",
			"img":  "icons/svg/upgrade.svg",
			"system": map[string]any{
				"slug":        t.Slug,
				"description": renderMD(md, t.Description),
				"category":    t.Category,
				"grants":      parseGrants(t.GrantsJSON),
			},
			"_key": "!items!" + t.FoundryID,
		}
		effects, err := talentActiveEffects(t.FoundryID, t.EffectsJSON)
		if err != nil {
			return fmt.Errorf("talent %s effects: %w", t.Slug, err)
		}
		if len(effects) > 0 {
			doc["effects"] = effects
		}
		if err := writeYAML(filepath.Join(talentsDir, t.Slug+".yml"), doc); err != nil {
			return err
		}
	}

	for _, r := range in.Regions {
		cultures := make([]map[string]any, 0, len(r.Cultures))
		for _, c := range r.Cultures {
			cultures = append(cultures, map[string]any{
				"slug":            c.Slug,
				"weight":          c.Weight,
				"backgroundSlugs": c.BackgroundSlugs,
			})
		}
		doc := map[string]any{
			"_id":  r.FoundryID,
			"name": r.Label,
			"type": "origin",
			"img":  "icons/svg/village.svg",
			"system": map[string]any{
				"subType":         "region",
				"slug":            r.Slug,
				"description":     renderMD(md, r.Description),
				"bannerImg":       r.BannerImg,
				"grants":          emptyGrants(),
				"cultures":        cultures,
				"isFull":          true,
				"hitDie":         "1d6",
				"hitDiePriority": 0,
				"talentPicks":    map[string]int{"warrior": 0, "expert": 0, "any": 0},
				"arts":            emptyArtsBlock(),
				"saves":           defaultSaves(),
				"talentSlug":      "",
				"classSlugs":      []string{},
				"backgroundSlugs": []string{},
				"free":            map[string]any{"skillKey": "", "specSlug": ""},
				"growth":          emptyGrowth(),
			},
			"_key": "!items!" + r.FoundryID,
		}
		if err := writeYAML(filepath.Join(originsDir, "region."+r.Slug+".yml"), doc); err != nil {
			return err
		}
	}

	for _, r := range in.Races {
		doc := map[string]any{
			"_id":  r.FoundryID,
			"name": r.Label,
			"type": "origin",
			"img":  "icons/svg/mystery-man.svg",
			"system": map[string]any{
				"subType":         "race",
				"slug":            r.Slug,
				"description":     renderMD(md, r.Description),
				"grants":          emptyGrants(),
				"talentSlug":      r.TalentSlug,
				"classSlugs":      r.ClassSlugs,
				"cultures":        []any{},
				"isFull":          true,
				"hitDie":         "1d6",
				"hitDiePriority": 0,
				"talentPicks":    map[string]int{"warrior": 0, "expert": 0, "any": 0},
				"arts":            emptyArtsBlock(),
				"saves":           defaultSaves(),
				"backgroundSlugs": []string{},
				"free":            map[string]any{"skillKey": "", "specSlug": ""},
				"growth":          emptyGrowth(),
			},
			"_key": "!items!" + r.FoundryID,
		}
		if err := writeYAML(filepath.Join(originsDir, "race."+r.Slug+".yml"), doc); err != nil {
			return err
		}
	}

	for _, b := range in.Backgrounds {
		growth := make([]map[string]any, 8)
		for i := 0; i < 8; i++ {
			growth[i] = map[string]any{
				"skillKey": b.Growth[i].SkillKey,
				"specSlug": b.Growth[i].SpecSlug,
			}
		}
		doc := map[string]any{
			"_id":  b.FoundryID,
			"name": b.Label,
			"type": "origin",
			"img":  "icons/svg/book.svg",
			"system": map[string]any{
				"subType":     "background",
				"slug":        b.Slug,
				"description": renderMD(md, b.Description),
				"grants":      emptyGrants(),
				"free": map[string]any{
					"skillKey": b.FreeSkillKey,
					"specSlug": b.FreeSpecSlug,
				},
				"growth":         growth,
				"cultures":       []any{},
				"isFull":         true,
				"hitDie":         "1d6",
				"hitDiePriority": 0,
				"talentPicks":    map[string]int{"warrior": 0, "expert": 0, "any": 0},
				"arts":            emptyArtsBlock(),
				"saves":           defaultSaves(),
				"talentSlug":      "",
				"classSlugs":      []string{},
				"backgroundSlugs": []string{},
			},
			"_key": "!items!" + b.FoundryID,
		}
		if err := writeYAML(filepath.Join(originsDir, "background."+b.Slug+".yml"), doc); err != nil {
			return err
		}
	}

	for _, cl := range in.Classes {
		abilityKeys := cl.EffortAbilityKeys
		if abilityKeys == nil {
			abilityKeys = []string{}
		}
		slots := cl.SlotsByLevel
		if len(slots) != 10 {
			norm := make([]int64, 10)
			copy(norm, slots)
			slots = norm
		}
		doc := map[string]any{
			"_id":  cl.FoundryID,
			"name": cl.Label,
			"type": "origin",
			"img":  "icons/svg/wing.svg",
			"system": map[string]any{
				"subType":         "class",
				"slug":            cl.Slug,
				"description":     renderMD(md, cl.Description),
				"grants":          emptyGrants(),
				"isFull":         cl.IsFull,
				"hitDie":         cl.HitDie,
				"hitDiePriority": cl.HitDiePriority,
				"talentPicks": map[string]int64{
					"warrior": cl.TalentPicksWarrior,
					"expert":  cl.TalentPicksExpert,
					"any":     cl.TalentPicksAny,
				},
				"arts": map[string]any{
					"skillKey":        cl.EffortSkillKey,
					"abilityKeys":     abilityKeys,
					"slotsByLevel":    slots,
					"receiveTableKey": "",
					"artKeys":         []string{},
				},
				"saves": map[string]any{
					"primary": map[string]any{
						"save": cl.SavePrimary, "priority": cl.SavePrimaryPriority,
					},
					"secondary": map[string]any{
						"save": cl.SaveSecondary, "priority": cl.SaveSecondaryPriority,
					},
				},
				"talentSlugs":     cl.TalentSlugs,
				"talentSlug":      "",
				"cultures":        []any{},
				"classSlugs":      []string{},
				"backgroundSlugs": []string{},
				"free":            map[string]any{"skillKey": "", "specSlug": ""},
				"growth":          emptyGrowth(),
			},
			"_key": "!items!" + cl.FoundryID,
		}
		if err := writeYAML(filepath.Join(originsDir, "class."+cl.Slug+".yml"), doc); err != nil {
			return err
		}
	}

	for _, a := range in.Arts {
		doc := map[string]any{
			"_id":  a.FoundryID,
			"name": a.Label,
			"type": "art",
			"img":  "icons/svg/explosion.svg",
			"system": map[string]any{
				"slug":            a.Slug,
				"description":     renderMD(md, a.Description),
				"classSlug":       a.ClassSlug,
				"commitment":      a.Commitment,
				"effortCommitted": false,
				"concentrating":   false,
			},
			"_key": "!items!" + a.FoundryID,
		}
		effects, err := talentActiveEffects(a.FoundryID, a.EffectsJSON)
		if err != nil {
			return fmt.Errorf("art %s effects: %w", a.Slug, err)
		}
		if len(effects) > 0 {
			doc["effects"] = effects
		}
		if err := writeYAML(filepath.Join(artsDir, a.Slug+".yml"), doc); err != nil {
			return err
		}
	}
	return nil
}

// RenderDescriptionHTML turns Forge Markdown into HTML for packs / lang JSON.
func RenderDescriptionHTML(src string) string {
	return renderMD(goldmark.New(), src)
}

func renderMD(md goldmark.Markdown, src string) string {
	src = strings.TrimSpace(src)
	if src == "" {
		return ""
	}
	var buf bytes.Buffer
	if err := md.Convert([]byte(src), &buf); err != nil {
		return "<p>" + src + "</p>"
	}
	return strings.TrimSpace(buf.String())
}

func parseGrants(raw string) map[string]any {
	var m map[string]any
	if err := json.Unmarshal([]byte(raw), &m); err != nil {
		return emptyGrants()
	}
	return m
}

// talentActiveEffects turns stored effect JSON into Foundry Active Effect documents.
// Forge stores change mode as a string; Foundry v14 expects the same string on `type`
// (CONST.ACTIVE_EFFECT_CHANGE_TYPES). Writing `mode` is ignored and defaults to custom.
// Each effect needs its own LevelDB _key; the packer stores embedded effects separately.
func talentActiveEffects(itemID, raw string) ([]any, error) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" || trimmed == "[]" {
		return nil, nil
	}
	var effects []struct {
		FoundryID string `json:"foundryId"`
		Name      string `json:"name"`
		Img       string `json:"img"`
		Disabled  bool   `json:"disabled"`
		Changes   []struct {
			Key      string `json:"key"`
			Mode     string `json:"mode"`
			Value    string `json:"value"`
			Priority int    `json:"priority"`
		} `json:"changes"`
	}
	if err := json.Unmarshal([]byte(trimmed), &effects); err != nil {
		return nil, err
	}
	out := make([]any, 0, len(effects))
	for _, e := range effects {
		changes := make([]any, 0, len(e.Changes))
		for _, ch := range e.Changes {
			changes = append(changes, map[string]any{
				"key":      ch.Key,
				"type":     ch.Mode,
				"value":    ch.Value,
				"priority": ch.Priority,
			})
		}
		img := e.Img
		if img == "" {
			img = "icons/svg/aura.svg"
		}
		out = append(out, map[string]any{
			"_id":         e.FoundryID,
			"_key":        "!items.effects!" + itemID + "." + e.FoundryID,
			"name":        e.Name,
			"img":         img,
			"type":        "base",
			"disabled":    e.Disabled,
			"transfer":    true,
			"origin":      nil,
			"tint":        "#ffffff",
			"description": "",
			"statuses":    []any{},
			"flags":       map[string]any{},
			"duration": map[string]any{
				"startTime":  nil,
				"seconds":    nil,
				"combat":     nil,
				"rounds":     nil,
				"turns":      nil,
				"startRound": nil,
				"startTurn":  nil,
			},
			"changes": changes,
		})
	}
	return out, nil
}

func emptyGrants() map[string]any {
	return map[string]any{
		"skills":          []any{},
		"specializations": []any{},
		"abilities":       []any{},
	}
}

func defaultSaves() map[string]any {
	return map[string]any{
		"primary":   map[string]any{"save": "reflex", "priority": 0},
		"secondary": map[string]any{"save": "fortitude", "priority": 0},
	}
}

func emptyGrowth() []map[string]any {
	out := make([]map[string]any, 8)
	for i := range out {
		out[i] = map[string]any{"skillKey": "", "specSlug": ""}
	}
	return out
}

func writeYAML(path string, doc map[string]any) error {
	// Stable key order via yaml.Node is heavy; marshal then inject header.
	keys := make([]string, 0, len(doc))
	for k := range doc {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	ordered := yaml.Node{Kind: yaml.MappingNode}
	for _, k := range keys {
		var kn, vn yaml.Node
		_ = kn.Encode(k)
		_ = vn.Encode(doc[k])
		ordered.Content = append(ordered.Content, &kn, &vn)
	}
	var buf bytes.Buffer
	buf.WriteString(packHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&ordered); err != nil {
		return fmt.Errorf("encode %s: %w", path, err)
	}
	_ = enc.Close()
	return os.WriteFile(path, buf.Bytes(), 0o644)
}
